services:
  - type: web
    name: chatbot-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false 
      - key: CORS_ORIGIN
        value: http://localhost:5173